### ISSUE TITLE
Problem with bootstrap3-dialog

### ISSUE THREAD

**Issue by bSushil** [kartik-v/yii2-dialog#25]
I installed your gridview and when running, I got the following error:

        Invalid Parameter – yii\base\InvalidParamException
        The file or directory to be published does not exist: /[path to my application root]/vendor/bower/bootstrap3-dialog

I checked and found out that bootstrap3-dialog is in the folder bower-asset. So, I changed path to the source in the file kartik-v/yii2-dialog/DialogBootstrapAsset.php in line 26 into following:

        $this->setSourcePath('@vendor/bower-asset/bootstrap3-dialog');

This worked for me. I hope others don't come across this problem, and if they do, this information might be helpful for them.

**Comment by kartik-v** [comment]
This should not be needed. You need to check if your composer and bower asset installs are correct and you have installed packages via composer rather than manual.

The `@bower` alias should be read by yii to locate the bower-asset vendor - just like how [yii2-bootstrap extension does for BootstrapAsset here](https://github.com/yiisoft/yii2-bootstrap/blob/master/BootstrapAsset.php).

**Comment by sokollondon** [comment]
Same problem. It helped:
```
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
php composer.phar install
```
